models:
  - ../models/rtdetr_r50vd.yaml
  - ../models/dfine_nano.yaml
  - ../models/dfine_small.yaml
  - ../models/rfdetr_nano.yaml
  - ../models/rfdetr_small.yaml
  - ../models/rfdetr_medium.yaml
  - ../models/rfdetr_base.yaml
  - ../models/detr_r50.yaml
  - ../models/conditional_detr_r50.yaml
  - ../models/deformable_detr.yaml
  - ../models/yolos_tiny.yaml
  - ../models/yolos_small.yaml
