params:
  optimizer:
    type: categorical
    choices: [sgd, adamw]
  learning_rate:
    type: float
    low: 0.00001
    high: 0.01
    log: true
  weight_decay:
    type: categorical
    choices: [0.0001, 0.0005, 0.001]
  momentum:
    type: categorical
    choices: [0.9]
  scheduler:
    type: categorical
    choices: [step, cosine]
