key: yolos_tiny
backend: hf_trainer
detector_pretraining_dataset: coco
model_name_or_path: hustvl/yolos-tiny
preprocess:
  resize_mode: shortest_edge
  shortest_edge: 512
  longest_edge: 1333
params: {}
