key: carpk_controlled

dataset_file: ../dataset_refs/carpk.yaml
class_space_file: ../class_spaces/traffic6.yaml
recipe_file: ../recipes/controlled_native.yaml
model_group_file: ../model_groups/detection_main.yaml

run_template:
  run_key: "{model_key}_{dataset_key}_{protocol}"
  output_dir: "runs/{model_key}/{dataset_key}/{protocol}"
  tuning_study_name: "{model_key}_{dataset_key}_{protocol}"
  tuning_output_dir: "runs/hpo/{model_key}_{dataset_key}_{protocol}"
  final_output_dir: "runs/{model_key}/{dataset_key}/{protocol}/final"
  wandb_project: "{dataset_key}_{protocol}"

backend_defaults:
  ultralytics:
    train:
      loader:
        num_workers: 16
        pin_memory: true
        persistent_workers: true
        prefetch_factor: 4
        decode_backend: opencv

  hf_trainer:
    train:
      loader:
        num_workers: 8
        pin_memory: true
        persistent_workers: true
        prefetch_factor: 4
        decode_backend: opencv

  torchvision:
    train:
      loader:
        num_workers: 8
        pin_memory: true
        persistent_workers: true
        prefetch_factor: 4
        decode_backend: opencv

tags:
  - carpk
  - controlled
