key: hazydet
root: source_datasets/hazydet
source_format: coco

default_condition: haze
default_domain: aerial
default_is_synthetic:
bbox_policy: clip

splits:
  train:
    paths:
      images: train/hazy_images
      annotations: train/train_coco.json
    condition: haze
    domain: aerial
    is_synthetic: true

  val:
    paths:
      images: val/hazy_images
      annotations: val/val_coco.json
    condition: haze
    domain: aerial
    is_synthetic: true

  test:
    paths:
      images: test/hazy_images
      annotations: test/test_coco.json
    condition: haze
    domain: aerial
    is_synthetic: true

class_map:
  car: car
  truck: truck
  bus: bus

ignore_labels: []
