key: hazydet_real
root: source_datasets/hazydet
source_format: coco

default_condition: haze
default_domain: aerial
default_is_synthetic: false
bbox_policy: clip

splits:
  train:
    paths:
      images: real_world/train
      annotations: real_world/train_real.json
    condition: haze
    domain: aerial
    is_synthetic: false

  test:
    paths:
      images: real_world/test
      annotations: real_world/test_real.json
    condition: haze
    domain: aerial
    is_synthetic: false

class_map:
  car: car
  truck: truck
  bus: bus

ignore_labels: []
